package com.example.genjutsucom

var AbecedarioList  = mutableListOf(
    Categorias(
        "1",
        "A",
        R.drawable.a.toString()
    ),
    Categorias(
        "2",
        "B",
        R.drawable.b.toString()
    ),
    Categorias(
        "3",
        "C",
        R.drawable.c.toString()
    ),
    Categorias(
        "4",
        "D",
        R.drawable.d.toString()
    ),
    Categorias(
        "5",
        "E",
        R.drawable.e.toString()
    ),
    Categorias(
        "6",
        "F",
        R.drawable.f.toString()
    ),
    Categorias(
        "7",
        "G",
        R.drawable.g.toString()
    ),
    Categorias(
        "8",
        "H",
        R.drawable.h.toString()
    ),
    Categorias(
        "9",
        "I",
        R.drawable.i.toString()
    ),
    Categorias(
        "10",
        "J",
        R.raw.j.toString()
    ),
    Categorias(
        "11",
        "K",
        R.raw.k.toString()
    ),
    Categorias(
        "12",
        "L",
        R.drawable.l.toString()
    ),
    Categorias(
        "13",
        "Ll",
        R.raw.ll.toString()
    ),
    Categorias(
        "14",
        "M",
        R.drawable.m.toString()
    ),
    Categorias(
        "15",
        "N",
        R.drawable.n.toString()
    ),
    Categorias(
        "16",
        "Ñ",
        R.raw.nie.toString()
    ),
    Categorias(
        "17",
        "O",
        R.drawable.o.toString()
    ),
    Categorias(
        "18",
        "P",
        R.drawable.p.toString()
    ),
    Categorias(
        "19",
        "Q",
        R.raw.q.toString()
    ),
    Categorias(
        "20",
        "R",
        R.drawable.r.toString()
    ),
    Categorias(
        "21",
        "Rr",
        R.raw.rr.toString()
    ),
    Categorias(
        "22",
        "S",
        R.drawable.s.toString()
    ),
    Categorias(
        "23",
        "T",
        R.drawable.t.toString()
    ),
    Categorias(
        "24",
        "U",
        R.drawable.u.toString()
    ),
    Categorias(
        "24",
        "V",
        R.drawable.v.toString()
    ),
    Categorias(
        "26",
        "W",
        R.drawable.w.toString()
    ),
    Categorias(
        "27",
        "X",
        R.raw.x.toString()
    ),
    Categorias(
        "28",
        "Y",
        R.drawable.y.toString()
    ),
    Categorias(
        "29",
        "Z",
        R.raw.z.toString()
    ),
)